// Copyright 2026 The ODML Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package litert.lm.proto;

import "runtime/proto/image_gen_model_type.proto";

option java_multiple_files = true;
option java_outer_classname = "ImageGenMetadataOuterClass";

// Parameters for Image Generation models.
message ImageGenMetadata {
  enum TfLiteModelType {
    // Placeholder for unspecified model type.
    TF_LITE_MODEL_TYPE_UNSPECIFIED = 0;

    // Monolithic 3-graph flow/diffusion components (e.g. BonsaiFlux2) and
    // shared image encoder/decoder components.
    TF_LITE_TEXT_ENCODER = 1;
    TF_LITE_IMAGE_DENOISER = 2;
    TF_LITE_IMAGE_DECODER = 3;
    TF_LITE_IMAGE_ENCODER = 4;

    // Sharded text encoder components (e.g. Flux2Klein ke_enc0..2).
    TF_LITE_TEXT_ENCODER_0 = 100;
    TF_LITE_TEXT_ENCODER_1 = 101;
    TF_LITE_TEXT_ENCODER_2 = 102;

    // Sharded version of the denoiser based on diffusion transformer (e.g.
    // Flux2Klein kc_*).
    TF_LITE_DIFFUSION_TRANSFORMER_INITIAL = 200;
    TF_LITE_DIFFUSION_TRANSFORMER_FINAL = 201;
    TF_LITE_DIFFUSION_TRANSFORMER_SINGLE_BLOCK_0 = 210;
    TF_LITE_DIFFUSION_TRANSFORMER_SINGLE_BLOCK_1 = 211;
    TF_LITE_DIFFUSION_TRANSFORMER_SINGLE_BLOCK_2 = 212;
    TF_LITE_DIFFUSION_TRANSFORMER_SINGLE_BLOCK_3 = 213;
    TF_LITE_DIFFUSION_TRANSFORMER_DOUBLE_BLOCK_0 = 220;
    TF_LITE_DIFFUSION_TRANSFORMER_DOUBLE_BLOCK_1 = 221;
  }

  // Image generation model type.
  ImageGenModelType image_gen_model_type = 1;
}
